language: bash
env:
  global:
  - BUILD_NAME=ExampleProjectName
services:
- docker
before_install:
- export UNITY_LICENSE_CONTENT=`cat Unity_v2020.x.ulf`
- docker pull gableroux/unity3d:2020.1.4f1
jobs:
  include:
  - stage: test
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=editmode IMAGE_NAME=gableroux/unity3d:2020.1.4f1
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: test
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=playmode IMAGE_NAME=gableroux/unity3d:2020.1.4f1
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: build
    env: BUILD_TARGET=Android IMAGE_NAME=gableroux/unity3d:2020.1.4f1-android
    script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "./Builds/"
